### ISSUE TITLE
dind container starts in port tls 2376 

### ISSUE THREAD

**Issue by cnunez007** [g0t4/course-implementing-self-hosted-docker-registry#1]
modify docker-compose.yml and add DOCKER_TLS_CERTDIR: ""

```
version: "3.5"

services:
  learning-registry:
    image: registry:2.6.2
  learning-jenkins:
    build: ./learning-jenkins
    volumes:
      - learning-jenkins-home:/var/jenkins_home
    ports:
      - "8190:8080"
    environment:
      DOCKER_HOST: tcp://dind:2375
  vetted-registry:
    image: registry:2.6.2
    ports:
      - "55000:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
  requestbin:
    image: weshigbee/requestbin
    ports:
      - "8000:8000"
  dind:
    image: docker:dind
    privileged: true
    environment:
       DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-data-root:/var/lib/docker
    command: [
      "--insecure-registry", "learning-registry:5000",
      "--insecure-registry", "vetted-registry:5000",
    ]


volumes:
  learning-jenkins-home:
  dind-data-root:
```
